### ISSUE TITLE
Unable to use modified bootstrap $primary variable

### ISSUE THREAD

**Issue by imtiazShakil** [ttskch/select2-bootstrap4-theme#46]
In my `styles.scss`,
I import `_variables.scss` to modify boostrap default `$blue` variable which changes bootstrap's `$primary` colour.

but this change is not picked up by your `layout.scss` because you are importing bootstrap variables again.
```scss
// layout.scss
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
```

Because of this mouse hovered item doesn't display the right colour:
```scss
    // mouse hovered item
    .select2-results__option--highlighted,
    .select2-results__option--highlighted.select2-results__option[aria-selected=true] {
        background-color: $primary;
        color: $light;
    }
```
