### ISSUE TITLE
Clear button x is not centered.

### ISSUE THREAD

**Issue by VictorioBerra** [ttskch/select2-bootstrap4-theme#6]
```css
/* Fix for select2-bootstrap4-theme clear buttons on dropdowns */
.select2-container--bootstrap4 .select2-selection__clear {
    line-height: .95em;
    padding-left: 0.26em;
}
```
